### ISSUE TITLE
Swift 3.0 conversion errors

### ISSUE THREAD

**Issue by Sergtsaeb** [learn-co-curriculum/swift-deli-counter#4]
After conversion, the project is having trouble testing due to the errors popping up in the swift-deli-counterTests file as well as a linker command error in the swift-deli-counter file. In addition, the Quick module is not found.

**Comment by 8bitramen** [comment]
i too am having this issue which is problematic considering i can't finish and do my technical interview until this is fixed.

**Comment by JessRudder** [comment]
@JimCampagno any insight on the errors mentioned above?  Is it an issue with the lab or possibly an environment issue we can help them resolve?

**Comment by JimCampagno** [comment]
@JessRudder Going to spend the time now to perfect this and fix everything in this lab.

**Comment by JimCampagno** [comment]
@8bitramen I've updated this lab completely. It's an entirely diff. lab (with the main theme of working with `Array`s staying the same). All that being said.. if you've already completed this lab (meaning the older version) know that that is fine and something you can walk through on your technical interview. I've kept the older version on a branch labeled `old`. 

Feel free (if you have the time) to complete the newer version which still involves a deli (at some level). But there's no obligation as you've attempted and completed the older version of this lab before I made any changes.

As far as the technical interview is concerned. If you find the tests aren't adhering to your _correct_ implementation, then I would ignore the tests. During your technical interview, you will be walking through explaining the methods you've made. There's no... "HEY, you're tests aren't working.. this is bad, explain yourself" moment. 

Let me know if I can help you any further. I'm closing this issue for now. Feel free to send me an e-mail as well and I can step through your problem in more detail if you find it's holding you back from completing the lab. jim@flatironschool.com

**Comment by 8bitramen** [comment]
I managed to get it to work after I made the fixes to the empty arrays. I was running my own tests and was confident the code was correct. Thank you though, I had to reschedule the technical interview for tomorrow at 4:30 since I couldn't get the day off for when i originally planned. I look forward to chatting! I hope my fixes helped, since I imagine other student may have gotten the error
