### ISSUE TITLE
Quick Error

### ISSUE THREAD

**Issue by tjcarney89** [learn-co-curriculum/swift-deli-counter#5]
Every time I try to run the tests, there is an error that tells me that the Quick module does not exist. In addition, my build is failing because it says that there isn't a return statement in my first function, even though there is.

**Comment by JimCampagno** [comment]
@tjcarney89 This is something you've written in Oct-2016, sorry for not responding to this! I've completely changed this lab to where it should be more fun to complete (I hope!) and it shouldn't be giving you those errors you were receiving back then.
